### ISSUE TITLE
代码完成度咨询

### ISSUE THREAD

**Issue by ligai322** [birchgrove/webrtc#1]
你好，请问你的这个仓库已经可以正常运行了吗，h265编码是否支持在浏览器端进行显示

**Comment by birchgrove** [comment]
> 你好，请问你的这个仓库已经可以正常运行了吗，是否支持在浏览器端进行显示

这个代码主要是作为服务器端使用的，仅仅是将[owt-deps-webrtc](https://github.com/open-webrtc-toolkit/owt-deps-webrtc)的h265相关代码合并到了`m85`的分支，仅测试了`Android`客户端硬解码，浏览器端没有做测试

**Comment by ligai322** [comment]
> > 你好，请问你的这个仓库已经可以正常运行了吗，是否支持在浏览器端进行显示
> 
> 这个代码主要是作为服务器端使用的，仅仅是将[owt-deps-webrtc](https://github.com/open-webrtc-toolkit/owt-deps-webrtc)的h265相关代码合并到了`m85`的分支，仅测试了`Android`客户端硬解码，浏览器端没有做测试

谢谢
